name: flutter_weather_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-149.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  injectable: ^1.5.3
  get_it: ^7.2.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  injectable_generator:  
  build_runner:  

  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
